# Generated by Django 3.2.8 on 2021-10-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100)),
                ('pain_type', models.CharField(max_length=100)),
                ('blood_pressure', models.CharField(max_length=100)),
                ('cholesterol', models.CharField(max_length=100)),
                ('blood_sugar', models.CharField(max_length=100)),
                ('ecg', models.CharField(max_length=100)),
                ('hart_rate', models.CharField(max_length=100)),
                ('exang', models.CharField(max_length=100)),
                ('old_peak', models.CharField(max_length=100)),
                ('slope', models.CharField(max_length=100)),
                ('ca', models.CharField(max_length=100)),
                ('thal', models.CharField(max_length=100)),
            ],
        ),
    ]
