# Generated by Django 3.2.8 on 2021-10-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasesmodel',
            name='female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diseasesmodel',
            name='male',
            field=models.BooleanField(default=False),
        ),
    ]
